hepsi: derle calistir 

derle : 
	g++ -I ./include/ -o ./lib/SumOfDigit.o -c ./src/SumOfDigit.cpp 
	g++ -I ./include/ -o ./lib/Factorial.o -c ./src/Factorial.cpp
	g++ -I ./include/ -o ./lib/ArrayList.o -c ./src/ArrayList.cpp 
	g++ -I ./include/ -o ./lib/Multiply.o -c ./src/Multiply.cpp 
	g++ -I ./include/ -o ./bin/Main ./lib/SumOfDigit.o ./lib/Factorial.o ./lib/ArrayList.o ./lib/Multiply.o ./src/Main.cpp 
calistir :
	./bin/Main